// Copyright 2026 Velle Sinclair.
//
// Simplified BSD License or GPLv3, like the rest of this tree.

// The OpenGL dispatch table of a Mac OS X 10.4 AGL or CGL context. Code
// built with aglMacro.h calls (*ctx->disp.entry)(ctx->rend, ...), so a
// context's table holds one thunk per entry, in gliDispatch.h order; each
// ignores the renderer pointer and forwards to the real GL function.
// gl_dispatch.c is generated by tools/gen_gl_dispatch.py.

#ifndef HLE_GL_DISPATCH_H_
#define HLE_GL_DISPATCH_H_

extern void* const hle_gl_thunks[];
extern const int hle_gl_thunk_count;

// Points the thunks at GL functions found by name. Returns how many entries
// found nothing; those log once when called and do nothing.
int hle_gl_resolve(void* (*lookup)(const char* name));

// The gliDispatch.h name of an entry, for messages.
const char* hle_gl_entry_name(int entry);

#endif  // HLE_GL_DISPATCH_H_
