#!/usr/bin/env python3
# Copyright 2026 Velle Sinclair.
#
# Simplified BSD License or GPLv3, like the rest of this tree.
"""Generates hle/gl_dispatch.c, the OpenGL dispatch table of a Mac OS X 10.4
AGL or CGL context.

Code built with aglMacro.h does not import glFoo. It calls
(*agl_ctx->disp.entry)(agl_ctx->rend, ...), so every entry of the context's
dispatch table needs a function with Apple's signature that forwards to the
real GL function.

  tools/gen_gl_dispatch.py gliDispatch.h aglMacro.h > hle/gl_dispatch.c

Both headers come from the Mac OS X 10.4u SDK, OpenGL.framework and
AGL.framework, and are not part of this tree.
"""

import re
import sys

# Apple's GL types by size on i386, where long is 32 bits.
GL_TYPES = {
    'GLenum': 'uint32_t',
    'GLboolean': 'uint8_t',
    'GLbitfield': 'uint32_t',
    'GLbyte': 'int8_t',
    'GLshort': 'int16_t',
    'GLint': 'int32_t',
    'GLsizei': 'int32_t',
    'GLubyte': 'uint8_t',
    'GLushort': 'uint16_t',
    'GLuint': 'uint32_t',
    'GLfloat': 'float',
    'GLclampf': 'float',
    'GLdouble': 'double',
    'GLclampd': 'double',
    'GLvoid': 'void',
    'GLchar': 'char',
    'GLcharARB': 'char',
    'GLhandleARB': 'uint32_t',
    'GLintptr': 'int32_t',
    'GLsizeiptr': 'int32_t',
    'GLintptrARB': 'int32_t',
    'GLsizeiptrARB': 'int32_t',
}

# Apple extensions with a portable equivalent of the same signature.
EQUIVALENTS = {
    'glBindVertexArrayAPPLE': ['glBindVertexArray'],
    'glDeleteVertexArraysAPPLE': ['glDeleteVertexArrays'],
    'glGenVertexArraysAPPLE': ['glGenVertexArrays'],
    'glIsVertexArrayAPPLE': ['glIsVertexArray'],
}


def parse_dispatch(text):
    body = re.search(
        r'typedef\s+struct\s+__GLIFunctionDispatchRec\s*\{(.*?)\}\s*'
        r'GLIFunctionDispatch', text, re.S).group(1)
    body = re.sub(r'/\*.*?\*/', '', body, flags=re.S)
    entries = []
    for decl in body.split(';'):
        decl = ' '.join(decl.split())
        if not decl:
            continue
        m = re.match(r'(.+?)\(\s*\*\s*(\w+)\s*\)\s*\((.*)\)$', decl)
        if not m:
            sys.exit('cannot parse dispatch entry: ' + decl)
        ret, name, params = m.group(1).strip(), m.group(2), m.group(3)
        params = [p.strip() for p in params.split(',')]
        if not params[0].startswith('GLIContext'):
            sys.exit('first parameter is not the context: ' + decl)
        entries.append((ret, name, params[1:]))
    return entries


def parse_macros(text):
    names = {}
    lines = text.splitlines()
    for i, line in enumerate(lines):
        m = re.match(r'#define\s+(gl\w+)\(.*\)\s*\\\s*$', line)
        if m and i + 1 < len(lines):
            d = re.search(r'->disp\.(\w+)\)', lines[i + 1])
            if d:
                names.setdefault(d.group(1), []).append(m.group(1))
    aliases = {}
    for m in re.finditer(r'^#define\s+(gl\w+)\s+(gl\w+)\s*$', text, re.M):
        aliases.setdefault(m.group(2), []).append(m.group(1))
    for gl_names in names.values():
        for n in list(gl_names):
            gl_names.extend(aliases.get(n, []))
            gl_names.extend(EQUIVALENTS.get(n, []))
    return names


def c_type(apple_type):
    def replace(m):
        word = m.group(0)
        if word.startswith('GL') and word not in GL_TYPES:
            sys.exit('unknown GL type: ' + word)
        return GL_TYPES.get(word, word)
    return re.sub(r'\b\w+\b', replace, apple_type)


def split_param(param, index):
    """(type, name) of a parameter, naming unnamed ones."""
    param = param.replace('*', ' * ')
    tokens = param.split()
    if len(tokens) > 1 and tokens[-1] != '*' and tokens[-1] not in GL_TYPES \
            and tokens[-1] not in ('const', 'void'):
        return ' '.join(tokens[:-1]), tokens[-1]
    return ' '.join(tokens), 'a%d' % index


def main():
    entries = parse_dispatch(open(sys.argv[1], encoding='latin-1').read())
    names = parse_macros(open(sys.argv[2], encoding='latin-1').read())
    out = []
    emit = out.append
    emit('// Generated by tools/gen_gl_dispatch.py from gliDispatch.h and')
    emit('// aglMacro.h of the Mac OS X 10.4u SDK. Do not edit.')
    emit('')
    emit('#include <stdint.h>')
    emit('#include <stdio.h>')
    emit('')
    emit('#include "gl_dispatch.h"')
    emit('')
    emit('#define ENTRIES %d' % len(entries))
    emit('')
    emit('static void* gl[ENTRIES];')
    emit('')
    emit('// Candidate GL names per entry, NULL-terminated.')
    for i, (_, name, _) in enumerate(entries):
        candidates = names.get(name, [])
        emit('static const char* const n%d[] = { %s };' % (
            i, ', '.join(['"%s"' % c for c in candidates] + ['NULL'])))
    emit('static const char* const* const kCandidates[ENTRIES] = {')
    for i in range(len(entries)):
        emit('  n%d,' % i)
    emit('};')
    emit('')
    emit('static const char* const kEntryNames[ENTRIES] = {')
    for _, name, _ in entries:
        emit('  "%s",' % name)
    emit('};')
    emit('')
    emit('static void missing(int entry) {')
    emit('  static uint8_t said[ENTRIES];')
    emit('  if (!said[entry]) {')
    emit('    said[entry] = 1;')
    emit('    fprintf(stderr, "hle: OpenGL has nothing for dispatch entry %s\\n",')
    emit('            kEntryNames[entry]);')
    emit('  }')
    emit('}')
    emit('')
    for i, (ret, name, params) in enumerate(entries):
        ret_c = c_type(ret)
        typed = [split_param(p, k) for k, p in enumerate(params)
                 if p not in ('void', 'GLvoid')]
        decl_params = ', '.join(['void* ctx'] +
                                ['%s %s' % (c_type(t), n) for t, n in typed])
        arg_types = ', '.join(c_type(t) for t, _ in typed) or 'void'
        args = ', '.join(n for _, n in typed)
        if ret_c == 'void':
            emit('static void t%d(%s) {' % (i, decl_params))
            emit('  if (!gl[%d]) {' % i)
            emit('    missing(%d);' % i)
            emit('    return;')
            emit('  }')
            emit('  ((void (*)(%s))gl[%d])(%s);' % (arg_types, i, args))
        elif ret_c == 'uint8_t':
            # A GLboolean result fills all of EAX for a Darwin caller.
            emit('static uint32_t t%d(%s) {' % (i, decl_params))
            emit('  if (!gl[%d]) {' % i)
            emit('    missing(%d);' % i)
            emit('    return 0;')
            emit('  }')
            emit('  return ((uint8_t (*)(%s))gl[%d])(%s);' % (arg_types, i, args))
        else:
            emit('static %s t%d(%s) {' % (ret_c, i, decl_params))
            emit('  if (!gl[%d]) {' % i)
            emit('    missing(%d);' % i)
            emit('    return 0;')
            emit('  }')
            emit('  return ((%s (*)(%s))gl[%d])(%s);' % (ret_c, arg_types, i, args))
        emit('}')
        emit('')
    emit('void* const hle_gl_thunks[] = {')
    for i in range(len(entries)):
        emit('  (void*)t%d,' % i)
    emit('};')
    emit('')
    emit('const int hle_gl_thunk_count = ENTRIES;')
    emit('')
    emit('int hle_gl_resolve(void* (*lookup)(const char* name)) {')
    emit('  int unresolved = 0;')
    emit('  for (int i = 0; i < ENTRIES; i++) {')
    emit('    gl[i] = NULL;')
    emit('    for (const char* const* n = kCandidates[i]; *n && !gl[i]; n++) {')
    emit('      gl[i] = lookup(*n);')
    emit('    }')
    emit('    unresolved += gl[i] == NULL;')
    emit('  }')
    emit('  return unresolved;')
    emit('}')
    emit('')
    emit('const char* hle_gl_entry_name(int entry) {')
    emit('  return entry >= 0 && entry < ENTRIES ? kEntryNames[entry] : NULL;')
    emit('}')
    print('\n'.join(out))


if __name__ == '__main__':
    main()
